### ISSUE TITLE
Unable to locate generated sources

### ISSUE THREAD

**Issue by lbhdc** [seh/rules_kustomize#2]
Hey! I am using a genrule to generate to template my manifests. When I include these sources in the `kustomization` rule, it fails to find them. 

```shell
Error: accumulating resources: accumulation err='accumulating resources from 'envoy_deployment.yaml': open /home/$USER/Repository/$REPO/envoy_deployment.yaml: no such file or directory': must build at directory: not a valid directory: evalsymlink failure on '/home/$USER/Repository/$REPO/envoy_deployment.yaml' : lstat /home/$USER/Repository/$REPO/envoy_deployment.yaml: no such file or directory
```

The `kustomize` rule is searching for the file in the source directory (it uses the dir of the BUILD file that the rule is called in) instead of looking in runfiles or sources files in the exec dir.

I saw there was a test for a generated kustomize.yaml, and for a file embedded in a config map referenced by this generated file. But I haven't seen one for the generated files passed to `srcs` (my use case). 

I could use some pointers on how to use generated manifests in `srcs`, and it would be helpful if there were a test case doing this that I could reference and poke at :grin:

**Comment by seh** [comment]
Per the project documentation's section titled ["Bazel's Sandbox and Load Restrictors"](https://github.com/seh/rules_kustomize#bazel-s-sandbox-and-load-restrictors), this may be due to _kustomize_ finding a symbolic link pointing to your source file named _envoy_deployment.yaml_, though it looks like you've left interpolation placeholders in the path:
> not a valid directory:
>   evalsymlink failure on '/home/$USER/Repository/$REPO/envoy_deployment.yaml':
> lstat /home/$USER/Repository/$REPO/envoy_deployment.yaml:
> no such file or directory

Did you expect that the "$USER" and "$REPO" path components would have been interpolated by the time that _kustomize_ sees them?

**Comment by seh** [comment]
I thought that _sandoxfs_ still works in Bazel version 6.4.0, but I know that it no longer works in version 7.0.0.

I've used this ruleset with lots of generated source files, so the scenario you're describing sounds like it normally works fine. Well, thinking about this more, it depends on how you're referring to these files from your _kustomization_ file's "resources" field.

The ruleset [collects all the referenced files into runfiles](https://github.com/seh/rules_kustomize/blob/7fde84479c3fb3f0107fcab970e4412b008a09fd/kustomize/kustomize.bzl#L100-L107) when [you use the `kustomized_resources` macro](https://github.com/seh/rules_kustomize/blob/7fde84479c3fb3f0107fcab970e4412b008a09fd/kustomize/kustomize.bzl#L242-L246). When it later invokes the _kustomize_ tool, [it supplies the path to the _kustomization_ root directory within that expanded runfiles directory tree](https://github.com/seh/rules_kustomize/blob/7fde84479c3fb3f0107fcab970e4412b008a09fd/kustomize/kustomize-build-from-runfiles#L16-L22).

If you build a `kustomized_resources` target with the `--sandbox_debug` command-line flag enabled, are you able to go inspect that directory that _kustomize_ used as its _kustomization_ root to see if your generated files are in there?

**Comment by seh** [comment]
I have seen that error reported from _sandboxfs_ on coworkers' machines, yet never on my own, which made it much harder for me to try to diagnose. It may have had something to do with the processor architecture in use (e.g. macOS atop Intel versus Apple M[1-3].

I'm glad to hear that you figured it out, and thank you for the kind words about what's here. If you find something else that you can't figure out or that appears to be broken, please follow up. I don't get to use this ruleset as much over the last few months, but I want to either know that it still works as expected or find other maintainers who can ensure that it stays in good shape.
