### ISSUE TITLE
Don't make kustomize.yaml hard-coded

### ISSUE THREAD

**Issue by borg286** [seh/rules_kustomize#3]
Your kustomized_resources seems fixed on requiring the kustomization to be a hard-coded file named kustomization.yaml or the other 2 variants, but none of them allow one to specify a different file name.

My end goal is that I want to have one directory containing my base yamls, another directory containing my overlays. In this overlays folder I can have 0 or more flat files that kustomizes one of the base yamls. As an alternative to any of these flat file kustomizes I would like to generate the kustomize file.  

The problem is that I the kustomized_resources rule seems to be fixated on a single file called kustomize.yaml, rather than accepting the one specified in the file param in the kustomization target.

I know this isn't much of your problem, but more of kustomize itself, but the file that is to be kustomized is hard to figure out if it is generated or flat.  In bazel you have the ${location ...} capability so that you can find the base file, fetch it, and render the kustomization.  But with your examples it is all implicit, because the resources section in the kustomization.yaml file expects a file to be adjacent to it with that name. But if the file is generated by some bazel rule it is difficult to predict where that is going to be.

**Comment by seh** [comment]
You are misinterpreting the code. The `kustomization` rule (well, really, it's a macro wrapped around the `_kustomization` rule) [uses _kustomization.yaml_ as the **default** value for the "file" attribute](https://github.com/seh/rules_kustomize/blob/7fde84479c3fb3f0107fcab970e4412b008a09fd/kustomize/kustomize.bzl#L91-L92). This ruleset imposes no requirement on the name supplied for the _kustomization_ file. It's the _kustomize_ tool that [only accepts the three different names](https://github.com/kubernetes-sigs/kustomize/blob/f3fedac42997470040e1fd574ad2518fad47f61a/api/konfig/general.go#L6-L16).

You are free to specify [the "file" attribute](https://github.com/seh/rules_kustomize/blob/7fde84479c3fb3f0107fcab970e4412b008a09fd/kustomize/kustomize.bzl#L23-L26) for your `kustomization` targets. It's a single-file dependency attribute. It can point to any source file or target that generates a single file.

**Comment by borg286** [comment]
Why do you even have an option to set the "file" field if the tool won't accept any file not named that. Please update your documentation to say that the filename must be kustomization.yaml, and that for a given folder, only a single instance of the kustomization() build rule can exist. I got the vague impression that this might be the case with how often implicit file references were being used (kustomization() build rule, and the resources section in kustomization.yaml)


I misunderstood the purpose of the kustomization.yaml. It is simply glueing together some overlay files and then pointed to some base folder where to find the bases.

In that case I guess what I'd like to see more is an example where you have the base yaml files being generated, the overlay files being generated, then how on earth does one construct a kustomization.yaml file that sets the resources and patches section so it points to the proper locations?

I'd like an example where you generate some yaml, one for the base, one for the overlay, and another that spits out the kustomization.yaml file. This latter one would likely need some special handling because its resources and patches section would need to point to the right locations for the base and patches. Then how do we feed these into a kustomization() build rule? What I'd want to see is your code being capable of handling both flat yaml files and generated ones.

**Comment by seh** [comment]
> Why do you even have an option to set the "file" field if the tool won't accept any file not named that. Please update your documentation to say that the filename must be kustomization.yaml, and that for a given folder, only a single instance of the kustomization() build rule can exist. I got the vague impression that this might be the case with how often implicit file references were being used (kustomization() build rule, and the resources section in kustomization.yaml).

As I mentioned in https://github.com/seh/rules_kustomize/issues/3#issuecomment-1890656135, the _kustomize_ tool will accept three different file names. This ruleset cannot know ahead of time which of those three you intend to use, nor where the file will come from. You can reference a static source file, or a Bazel target that generates a single source file. That file does _not_ have to sit within the same directory as the Bazel package's root directory; it can sit within a subdirectory, and its basename can be any of the three accepted by _kustomize_.

**Comment by seh** [comment]
If you're still having trouble, please share an example of what you're trying to do, and I'll suggest a way to make it work.
